### ISSUE TITLE
[feature-request] Support `using namespace`

### ISSUE THREAD

**Issue by dosentmatter** [StartAutomating/PSMinifier#6]
Currently, all inputs to PSMinifier are passed in through the `$ScriptBlock` parameter. If the `$ScriptBlock` contains a `using namespace` statement, it is removed in the resulting compressed output, causing the code to potentially not work.
This feature request is to support compression of the `using namespace` statement.

Example:
```ps1
Compress-ScriptBlock -ScriptBlock ([Scriptblock]::Create(@"
using namespace System.Security.Cryptography
using namespace System.Windows.Forms
echo 1
echo 2
"@))

# output
echo 1;echo 2
```

Note that it seems like `using` statements can be concatenated on a single line:
```ps1
# works
using namespace System.Security.Cryptography; using namespace System.Windows.Forms;
```

The current workaround is just to manually prepend the using statements back after minification is done.

---

Background Info:

Script blocks don't support the `using` statement:
```ps1
{ using namespace System.Security.Cryptography; }

# output
ParserError:
Line |
   1 |  { using namespace System.Security.Cryptography; }
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | A 'using' statement must appear before any other statements in a script.
```

But it is possible to create a script block containing a `using` statement:

1. By using a string
```ps1
[Scriptblock]::Create('using namespace System.Security.Cryptography')
```

2. By using `Get-Command` on a `.ps1` file containing `using`:
```ps1
# test.ps1
using namespace System.Security.Cryptography
```
```
(Get-Command .\test.ps1).ScriptBlock

# output
using namespace System.Security.Cryptography
```

---

The `using` statements do appear in the AST as `$ScriptBlock.Ast.Extent` along with the rest of the code, but aren't currently being processed:
```ps1
[Scriptblock]::Create(@"
using namespace System.Security.Cryptography
using namespace System.Windows.Forms
echo 1
echo 2
"@).Ast.Extent

# output
File                :
StartScriptPosition : System.Management.Automation.Language.InternalScriptPosition
EndScriptPosition   : System.Management.Automation.Language.InternalScriptPosition
StartLineNumber     : 1
StartColumnNumber   : 1
EndLineNumber       : 4
EndColumnNumber     : 7
Text                : using namespace System.Security.Cryptography
                      using namespace System.Windows.Forms
                      echo 1
                      echo 2
StartOffset         : 0
EndOffset           : 95
```

One way to support this is to grab the `Extent.Text` field and parse the first few lines for `using` statements. I'm not sure if powershell has an API for a `.ps1` file AST instead of script block AST. A file AST probably would provide the tree for the using statements.

**Comment by dosentmatter** [comment]
Bonus:

Support `using module` and `using assembly` as well.

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_using?view=powershell-7.1

**Comment by StartAutomating** [comment]
@dosentmatter I believe I've fixed this.  Please take a look at a newer build when you get a chance.  Your example has been integrated as a test.

**Comment by dosentmatter** [comment]
@StartAutomating, thanks for the fixes, the latest version works for me now.
